name: Smooth Checkout
description: All the things you need during a Buildkite checkout
author: https://github.com/hasura
requirements: []
configuration:
  properties:
    skip_checkout:
      type: boolean
    clone_url:
      type: string
    clone_urls:
      type: array
    ref:
      type: string
  additionalProperties: false
