name: Smooth Checkout
description: All the things you need during a Buildkite checkout
author: https://github.com/hasura
requirements: []
configuration:
  properties:
    skip_checkout:
      type: boolean
    config:
      type: array
      items:
        type: object
        properties:
          url:
            type: string
          ref:
            type: string
        additionalProperties: false
  additionalProperties: false
