name: Smooth Git
description: Set up Git projects smoothly on Buildkite
author: https://github.com/hasura
requirements: []
configuration:
  properties:
    skip_checkout:
      type: boolean
  additionalProperties: false