#!/usr/bin/env bash

set -eo pipefail

function set_env() {
  local env_name=$1
  local env_value=$2
  export "${env_name}"="${env_value}"
  echo "${env_name}"="${!env_name}"
}

echo "--- :house_with_garden: Setting up environment"
set_env WORKSPACE "$HOME/buildkite-checkouts/$BUILDKITE_BUILD_ID/$BUILDKITE_JOB_ID"
