#!/usr/bin/env bash

set -eo pipefail

CHECKOUT_DIR="$HOME/buildkite-checkouts/$BUILDKITE_BUILD_ID/$BUILDKITE_JOB_ID"
if [ -d "$CHECKOUT_DIR" ]; then
    echo "Removing checkout directory $CHECKOUT_DIR ..."
    rm -r "$CHECKOUT_DIR"
fi
echo "Cleanup done!"
